2025-03-26 07:08:40,364 - INFO: Request: v1 | Query: a | Page: 1
2025-03-26 07:08:50,371 - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x1031f2360>, 'Connection to 35.200.185.69 timed out. (connect timeout=10)')': /v1/autocomplete?query=a&page=1
2025-03-26 07:09:01,379 - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103baf800>, 'Connection to 35.200.185.69 timed out. (connect timeout=10)')': /v1/autocomplete?query=a&page=1
2025-03-26 07:09:13,388 - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103baf890>, 'Connection to 35.200.185.69 timed out. (connect timeout=10)')': /v1/autocomplete?query=a&page=1
2025-03-26 07:09:23,393 - ERROR: Request exception: HTTPConnectionPool(host='35.200.185.69', port=8000): Max retries exceeded with url: /v1/autocomplete?query=a&page=1 (Caused by ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103bafad0>, 'Connection to 35.200.185.69 timed out. (connect timeout=10)'))
2025-03-26 07:09:23,393 - INFO: Request: v1 | Query: b | Page: 1
2025-03-26 07:09:33,397 - WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103bafc20>, 'Connection to 35.200.185.69 timed out. (connect timeout=10)')': /v1/autocomplete?query=b&page=1
2025-03-26 07:09:44,408 - WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103bfc050>, 'Connection to 35.200.185.69 timed out. (connect timeout=10)')': /v1/autocomplete?query=b&page=1
2025-03-26 07:09:56,417 - WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<urllib3.connection.HTTPConnection object at 0x103bfc140>, 'Connection to 35.200.185.69 timed out. (connect timeout=10)')': /v1/autocomplete?query=b&page=1
